services:
  mongodb:
    image: mongo:5.0
    container_name: mongo_aurora
    restart: on-failure
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${ADMIN_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${ADMIN_PWD}
      - MONGO_INITDB_DATABASE=${DB_NAME}
      - AURORA_USER=${AURORA_USER}
      - AURORA_PWD=${AURORA_PWD}
    ports:
      - ${DB_LOCAL_PORT}:27017
    volumes:
      - ./init.db:/docker-entrypoint-initdb.d
      - ./data:/data/db
